// <auto-generated />
using GroupProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupProject.Migrations.patient
{
    [DbContext(typeof(patientContext))]
    [Migration("20230329091028_firstSet")]
    partial class firstSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("GroupProject.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdmittedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Doctor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Guardian")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuardianTeleNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuaranceCom")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceComeNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsurancePolicy")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceRelation")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuredName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeleNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WardNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("payments")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
